version: "3"
services:
  server:
    image: gocd/gocd-server:v20.1.0
    ports:
      - "8156:8153"
      - "8154:8154"
    volumes:
      - ./data:/godata
      - ./data/home:/home/go
      - ./scripts/server:/docker-entrypoint.d
      - ./scripts/shared:/shared
    environment:
      - GO_SERVER_SYSTEM_PROPERTIES=-Dcruise.material.update.interval=2000 -Dmaterial.update.idle.interval=2000
    depends_on:
      - "gitserver"

  agent:
    image: gocd/gocd-agent-docker-dind:v20.1.0
    environment:
      - GO_SERVER_URL=https://server:8154/go
      - AGENT_AUTO_REGISTER_KEY=agent-autoregister-key
    volumes:
      - ./scripts/agent:/docker-entrypoint.d
      - ./scripts/shared:/shared
    depends_on:
      - "server"
      - "gitserver"

  gitserver:
    image: gocdcontrib/git-http-backend:v2
    ports:
      - "8155:80"
    volumes:
      - ./repositories:/git