format_version: 9

environments:
  dev:
    environment_variables:
      DEPLOYMENT: dev
    pipelines:
      - yaml_created_pipeline

pipelines:
  yaml_created_pipeline:
    group: yaml_group
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      gocd_demo:
        git: https://github.com/kiryl-z/gocd_demo.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - stage_1:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: manual
          allow_only_on_success: true
        jobs:
          demo_job:
            timeout: 0
            tasks:
            - exec:
                arguments:
                  - -c
                  - echo $SHELL $GO_PIPELINE_LABEL stage1
                command: /bin/bash
                run_if: passed

    - stage_2:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: true
        jobs:
          demo_job:
            timeout: 0
            tasks:
              - exec:
                  arguments:
                    - -c
                    - ./scripts/stage_2.sh
                  command: /bin/bash
                  run_if: passed

    - stage_3:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: manual
          allow_only_on_success: true
        jobs:
          demo_job:
            timeout: 0
            tasks:
              - exec:
                  arguments:
                    - -c
                    - echo $SHELL $GO_PIPELINE_LABEL stage3
                  command: /bin/bash
                  run_if: passed
